name: us_hub
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  get_storage:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  animated_splash_screen:
  lottie:
  geolocator:
  page_transition:
  interactive_bottom_sheet:
  google_maps_flutter:
  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  backdrop: ^0.9.1
  sliding_up_panel: ^2.0.0+1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arimo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Arimo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Arimo-SemiBold.ttf
          weight: 600
